services:
  db:
    image: postgres:16.0-alpine3.18
    env_file:
      - ./db/.env
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data:cached
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 3s
      retries: 3

  api:
    tty: true
    volumes:
      - ./api/:/home/docker/app
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./api/.env
    ports:
      - 8080:8080
    depends_on: 
      db:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  web:
    volumes:
      - ./web:/home/node/app
      - /home/node/app/node_modules
    build:
      context: ./web
      dockerfile: Dockerfile
    env_file:
      - ./web/.env
    ports:
      - 5173:5173
    